export const StoryConstant = {
  CREATE_STORY: 'CREATE_STORY',
  GET_OWN_STORIES: 'GET_OWN_STORIES',
  GET_SOTRY_ID: 'GET_SOTRY_ID',
  CREATE_CHAPPER: 'CREATE_CHAPPER',
  GET_ALL_STORIES: 'GET_ALL_STORIES',
  SEARCH_STORIES: 'SEARCH_STORIES',
};
